name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Debug working directory
      run: |
        echo "Current directory: $(pwd)"
        ls -la

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      working-directory: ${{ github.workspace }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit pytest

    - name: Run tests
      working-directory: ${{ github.workspace }}
      run: pytest

    - name: Lint code
      working-directory: ${{ github.workspace }}
      run: pre-commit run --all-files
